name: Imgshape
description: Imgshape
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.1
  supabase: ^2.9.1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  flutter_dropzone: ^4.2.1
  go_router: ^16.2.4
  #flutter_riverpod: ^3.0.0
  http: ^1.5.0
  jwt_decode: ^0.3.1
  logging: ^1.3.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  provider: ^6.0.5
  path: ^1.8.3
  cached_network_image: ^3.4.1
  archive: ^4.0.7
  pdf: ^3.11.3
  printing: ^5.14.2
  csv: ^6.0.0
  share_plus: ^12.0.1
  file_saver: ^0.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.0
  media_scanner: ^2.2.0 # Downgraded to match available version

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/logo.jpg

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"